### ISSUE TITLE
Predictions bugs in v1.8.6

### ISSUE THREAD

**Issue by Virmolian** [LezdCS/irl-link#131]
# Bug nr. 1
**Tested feature:** Timer of an ongoing 30 second long prediction.
**Expected result:** 30 second timer counts down until submissions are locked.
**Actual result:** Static and inaccurate time displayed for the time left to submit points.

# Bug nr. 2
**Tested feature:** Ending prediction and choosing the result in a pop-up.
**Expected result:** The pop-up in which the streamer picks the results closes after confirming the outcome.
**Actual result:** Pop-up stays open after paying out the winners of the prediction.

Payouts for winners and refunds for cancelled predictions work as expected.

[Video 1:](https://media.discordapp.net/attachments/816070094894399519/1152870574360637550/Record_2023-09-17-15-15-53.mp4) Demonstration of cancelling a prediction with a broken timer.
[Video 2:](https://media.discordapp.net/attachments/816070094894399519/1152870713666048090/Record_2023-09-17-15-17-18.mp4) Demonstration of ending a prediction by picking a result in the pop-up.

OS: Android 13, OxygenOS 13.1
Phone: OnePlus 8 Pro

**Comment by LezdCS** [comment]
Bug number 1 is now fixed.
Working on number 2 now
