### ISSUE TITLE
Tapping chat input field closes keyboard

### ISSUE THREAD

**Issue by Virmolian** [LezdCS/irl-link#132]
**Tested feature:** Interaction with the chat input field.
**Expected result:** Being able to tap the chat input field to reposition the cursor, select, copy or paste text.
**Actual result:** The entire keyboard closes.

https://github.com/LezdCS/irl-link/assets/144674733/3f1688c8-cb04-45b0-a004-e54109be6c8c

App version: 1.8.6
OS: Android 13, OxygenOS 13.1
Phone: OnePlus 8 Pro

**Comment by LezdCS** [comment]
Fixed in dev branch
