### ISSUE TITLE
Chat input is sent to the wrong chat when in multiple chatrooms

### ISSUE THREAD

**Issue by Virmolian** [LezdCS/irl-link#134]
Essentially the title.

I can recreate it pretty easily:
Open up the app.
Join an additional Twitch chat.
Type a message in the main chat.
If it doesn't appear, it was sent into the other chat.

The bug does not seem to persist after the app is restarted or the user manually opens the additionally joined chatroom and comes back to type in the main channel.

When joining two extra channels and then typing in the first chat, the messages are sent into the third, last joined chat.

v1.8.6
Android 13
OnePlus 8 Pro

**Comment by LezdCS** [comment]
Thanks! I indeed can reproduce it, I will try to fix it for the next update! However I won't put it in high priority as I think that it's rare for streamers to have multiple chat!
