### ISSUE TITLE
The entire app freezes when trying to adjust chat size

### ISSUE THREAD

**Issue by Virmolian** [LezdCS/irl-link#144]
Workaround: Clear your app data.

This started happening only today. It was working fine yesterday. 
When I open the app, everything works normally. As soon as I try to adjust the size of chat with the slider, everything becomes unresponsive to the point where I have to force stop the app.

https://github.com/LezdCS/irl-link/assets/144674733/3e603fbf-4257-475f-8099-1332ac323148

Version 1.9.4
Android 13
OnePlus 8 Pro

**Comment by Virmolian** [comment]
Update:

This bug has persisted and the app's performance has been getting worse. Increasing start-up time and worse app performance.

I usually force stop the app after I'm done using it, so I luckily saw that its size had grown to a strange amount.![IMG_20231220_121420.jpg](https://github.com/LezdCS/irl-link/assets/144674733/a078587b-4d43-4ca9-af17-2f68f487634e)

On both my phones the app was over 500MB in data.

I cleared all the data (had to set up my connections, browser sources, etc. again) and the 1 minute+ startup time and the slider bug where it completely freezes the app if you just touch it are gone. My app now launches into a usable state in about 14 seconds.

**Comment by LezdCS** [comment]
I need to investigate but I am currently on a 10 days holidays in France with no computers, sorry...
