### ISSUE TITLE
Dashboard shortcut bug

### ISSUE THREAD

**Issue by Virmolian** [LezdCS/irl-link#146]
One of the buttons I set up is supposed to type "!weather seoul" in chat.
Not sure how this happened:
![IMG_20231125_214439.jpg](https://github.com/LezdCS/irl-link/assets/144674733/cde8355c-522b-4128-b603-6c12de3c05ee)

Every time I use the button, it adds more \ 
![Screenshot_2023-11-25-21-52-28-61_6bf1dc6e7b3d4b64f0b3bdc9374575a0.jpg](https://github.com/LezdCS/irl-link/assets/144674733/ba1ef400-d642-4eb3-8448-d8864d0fd777)

Also, my other button stopped working entirely.

After deleting and re-adding them, they work as intended again.

v1.9.4
Android 13
OnePlus 8 Pro

**Comment by LezdCS** [comment]
Fixed @Virmolian
