### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by xKotelek** [LezdCS/irl-link#147]
Every time me on ios od my friend on android try to login we get error 405![image](https://github.com/LezdCS/irl-link/assets/98203141/c8c5bb2e-e08d-4b57-9219-7093da4d5033)

**Comment by LezdCS** [comment]
Oh that's odd, I can't reproduce it, let me check what could cause this on server side

**Comment by gvsyn** [comment]
![image](https://github.com/LezdCS/irl-link/assets/223082/f46dfd2a-226b-47cc-b4eb-5cb4d275023a)
Had the same since the 16th... Did you utterly clear your cache before trying to reproduce? (suspecting everything expired on my end)

**Comment by xKotelek** [comment]
> ![image](https://github.com/LezdCS/irl-link/assets/223082/f46dfd2a-226b-47cc-b4eb-5cb4d275023a)
> 
> Had the same since the 16th... Did you utterly clear your cache before trying to reproduce? (suspecting everything expired on my end)

no

**Comment by xKotelek** [comment]
i cleared cache reinstalled app and still error 405

**Comment by xKotelek** [comment]
> Oh that's odd, I can't reproduce it, let me check what could cause this on server side
now i keep getting error 400![image](https://github.com/LezdCS/irl-link/assets/98203141/094add7a-e27b-477b-aabc-c3cd959f74e8)

**Comment by LezdCS** [comment]
Sorry for the delay, I was away for holidays, I pushed a fix on the server yesterday, could you tell me if you still get the error ?

**Comment by gvsyn** [comment]
> Sorry for the delay, I was away for holidays, I pushed a fix on the server yesterday, could you tell me if you still get the error ?

Not any more. Thanks.
