### ISSUE TITLE
Browser tabs: http URLs not working

### ISSUE THREAD

**Issue by seba11** [LezdCS/irl-link#153]
When add http website always got error like in the screen:
![Screenshot_20240220_222244](https://github.com/LezdCS/irl-link/assets/7965273/a7d88d1f-80ea-4da4-9cca-d54a09ac30b6)

With https links works fine. 
It's usefull to have http support for ex. router page, belabox.local, etc.

Device: Samsung S20 (SM-G980F/DS)
OS: Android 13 One UI 5.1
APP: 1.9.6

**Comment by LezdCS** [comment]
Indeed we currently not allow HTTP urls, I'll add support for it in next version as the examples you gave a quite relevant!

**Comment by LezdCS** [comment]
Fixed on 1.9.8, sorry for the delay @seba11
