### ISSUE TITLE
Complete refactor to remove GetX

### ISSUE THREAD

**Issue by LezdCS** [LezdCS/irl-link#281]
GetX is slop and it was used at the beginning because the app was just supposed to be a small side project. Now IRL Link is getting bigger and bigger, it needs to be more "production ready".

It is not urgent and can wait as the app for now works well, but some part of the code looks bad and I overused GetX for many parts of the project.

**Comment by LezdCS** [comment]
Considering RiverPod for state management, GoRouter for routing.

Also getting Equatable away and use Freezed. 

For i18n, maybe intl but need to check other solutions available.

**Comment by SputNikPlop** [comment]
I think provider and flutter_localizations then we can work on reducing package dependencies
