### ISSUE TITLE
Support pinned message

### ISSUE THREAD

**Issue by LezdCS** [LezdCS/irl-link#297]
For Twitch (https://dev.twitch.tv/docs/pubsub/) : 

- Unpin object : 

> {
>     "topic": "pinned-chat-updates-v1.107285371",
>     "message": "{\"type\":\"unpin-message\",\"data\":{\"id\":\"e424e647-41bd-41b5-9265-005aa02b4885\",\"unpinned_by\":{\"id\":\"107285371\",\"display_name\":\"Lezd_\"},\"reason\":\"UNPIN\"}}"
> }

 - Pin object :

>  {
>     "topic": "pinned-chat-updates-v1.107285371",
>     "message": "{\"type\":\"pin-message\",\"data\":{\"id\":\"44c632f4-d0f6-4c60-8e50-5f09b2c0a20a\",\"pinned_by\":{\"id\":\"107285371\",\"display_name\":\"Lezd_\"},\"message\":{\"id\":\"e24ddba7-eb44-4710-ad2d-800f9562adec\",\"sender\":{\"id\":\"107285371\",\"display_name\":\"Lezd_\",\"badges\":[{\"id\":\"broadcaster\",\"version\":\"1\"},{\"id\":\"chatter-cs-go-2022\",\"version\":\"1\"}],\"chat_color\":\"#AA00CC\"},\"content\":{\"text\":\"ok\",\"fragments\":[{\"text\":\"ok\"}]},\"type\":\"MOD\",\"starts_at\":1729609832,\"updated_at\":1729609832,\"ends_at\":1729611032,\"sent_at\":1729609810}}}"
> }

For Kick : 
same webscoket as the other events

**Comment by SputNikPlop** [comment]
> For Twitch (https://dev.twitch.tv/docs/pubsub/) :

The pubsub system will be retired in six months https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043

**Comment by LezdCS** [comment]
I haven't found the pinned message feature on the twitch event sub so for now I use pub sub but indeed I will have to remove it in 6 months anyway
