### ISSUE TITLE
Webpage doesn't work after ver1.05 (Android)

### ISSUE THREAD

**Issue by HitoriGS** [LezdCS/irl-link#38]
After version 1.0.5, my embedded webpage stopped working and only displays a gray/white screen.

Phone: Samsung A52S
Version:1.0.5、1.0.6、1.3.0

**Comment by LezdCS** [comment]
Does your webpages urls contains https:// in front of them ? It should not be an issue if it's not the case but I want to make sure it's not a problem on some devices. 

Also it's pretty weird that I have no report from any crash on crashlytics related to webpages.

**Comment by LezdCS** [comment]
Ok I successfully reproduced the issue, it will be fixed in next version!

**Comment by LezdCS** [comment]
@HitoriGS i just release v1.3.1, it should fix your issue. Please let me know if it's not fixed!

**Comment by HitoriGS** [comment]
@LezdCS  Yes, it is fixed.  Thank you for your work!
