### ISSUE TITLE
Chat is flushing out in a random time

### ISSUE THREAD

**Issue by HitoriGS** [LezdCS/irl-link#75]
Hello, after the 1.5 version update, the chatroom messages will automatically disappear within a random time, usually within around 10 seconds. This makes it very easy for streamers to miss chat messages. The issue persists even after updating to version 1.6.

I am using a Samsung A52S smartphone, and I experience the same problem whether I download from GitHub or Google Play.

**Comment by LezdCS** [comment]
Since 1.5 I transitioned my chat code into a package (https://github.com/LezdCS/twitch_chat).

Thanks for letting me know, I will look into it asap.

**Comment by LezdCS** [comment]
@HitoriGS it should be fixed in the 1.6.2, will be on the store in few hours, let me know if you still encounter the issue! :)
