### ISSUE TITLE
Latin version of chatters names over localized 

### ISSUE THREAD

**Issue by LezdCS** [LezdCS/irl-link#79]
Some people don't have nicknames using Latin alphabet

Check how is it working with the twitch irc

**Comment by SputNikPlop** [comment]
Everyone has a latin name just some users have a localized name like in Japan.

**Comment by LezdCS** [comment]
> Everyone has a latin name just some users have a localized name like in Japan.

Does it show the localized in priority? I got a feedback saying it was but haven't checked it yet. If yes, any field in the irc that give the display name in Latin and not localized?

**Comment by SputNikPlop** [comment]
> > Everyone has a latin name just some users have a localized name like in Japan.
> 
> Does it show the localized in priority? I got a feedback saying it was but haven't checked it yet. If yes, any field in the irc that give the display name in Latin and not localized?

Localized is always the priority as that is how that user prefers their name to be addressed, if you did implement this I think showing both would be ideal and unsure how a mentioning said user would work properly.. I think latin is included in the message attached is a screenshot how RealtimeChat han
![IMG_1161](https://github.com/LezdCS/irl-link/assets/100245448/278223a3-a9e6-49ae-9e5e-1ccbd92b5fbe)
dles it

**Comment by LezdCS** [comment]
> > > Everyone has a latin name just some users have a localized name like in Japan.
> > 
> > Does it show the localized in priority? I got a feedback saying it was but haven't checked it yet. If yes, any field in the irc that give the display name in Latin and not localized?
> 
> Localized is always the priority as that is how that user prefers their name to be addressed, if you did implement this I think showing both would be ideal and unsure how a mentioning said user would work properly.. I think latin is included in the message attached is a screenshot how RealtimeChat handles it
> ![IMG_1161](https://github.com/LezdCS/irl-link/assets/100245448/278223a3-a9e6-49ae-9e5e-1ccbd92b5fbe)
> 

Yes I was indeed going to display it as it is on twitch, I'll take a look at how it works with the IRC! Thanks a lot.

**Comment by SputNikPlop** [comment]
@LezdCS so as in on twitch it kinda does it funny on the chat scroll back it only shows the latin name but live chat it only shows localized, perhaps you want to display it as it is in the screenshot above

**Comment by LezdCS** [comment]
> @LezdCS so as in on twitch it kinda does it funny on the chat scroll back it only shows the latin name but live chat it only shows localized, perhaps you want to display it as it is in the screenshot above

Oh I remember having both on twitch but yeah it will look like on your screen!
